source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!



target 'ReactUI_Example', :exclusive => true do
  pod 'ReactUI', :path => '../'
end

target 'ReactUI_Tests', :exclusive => true do
  pod 'ReactUI', :path => '../'

  pod 'Specta'
  pod 'Expecta'
end
